name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Ensure token available to all steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug if secret is injected
      - name: Verify SNYK_TOKEN
        run: |
          if [ -z "$SNYK_TOKEN" ]; then
            echo "❌ SNYK_TOKEN is empty! Check your GitHub Secrets."
            exit 1
          else
            echo "✅ SNYK_TOKEN is present."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Debug Snyk auth
        run: snyk auth --show-token

      # Snyk Code (SAST) scan with SARIF upload
      - name: Snyk Code (SAST)
        run: |
          snyk code test --org=my-org-slug --sarif-file-output=snyk-code.sarif || echo '{"version":"2.1.0","runs":[]}' > snyk-code.sarif

      - name: Debug SARIF content
        run: cat snyk-code.sarif

      - name: Upload Snyk Code results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      # Snyk Open Source dependency scan
      - name: Snyk Open Source (Dependencies)
        run: snyk monitor --org=my-org-slug --all-projects || true